#!/usr/bin/env bash

set -euo pipefail

abspath() {
    python -c "import os,sys; print os.path.abspath(sys.argv[1])" "$1"
}

proot="$(abspath "$(dirname "$0")"/..)"

redir() {
    printf "%s -> %s\n" "$1" "$2"
    aws --quiet s3 cp "$src" "${dest}/$1" --website-redirect "$2"
}

cd "$proot"

src=data/moved.html
dest=s3://presumably-de-sitebucket-i2nzci1gpkw3

redir /boot-react-native.html /getting-started-with-boot-react-native-part-1-up-and-running.html
redir /reagent.html /reagent-mysteries-part-1-vectors-and-sequences.html
redir /reagent-2.html /reagent-mysteries-part-2-reloading.html
